name: Build & Push Docker Image
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Docker Image
      run: |
        docker build . --file Dockerfile --tag ${GITHUB_SHA:0:8}
    - name: Push Build Image
      run: |
        echo ${{ github.token }} |  docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
        docker tag ${GITHUB_SHA:0:8} docker.pkg.github.com/wardcunningham/seran-wiki:${GITHUB_SHA:0:8}
        docker push docker.pkg.github.com/wardcunningham/seran-wiki:${GITHUB_SHA:0:8}
    - name: Push Latest Image
      if: github.ref == 'refs/heads/master'
      run: |
        echo ${{ github.token }} |  docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
        docker tag ${GITHUB_SHA:0:8} docker.pkg.github.com/wardcunningham/seran-wiki:latest
        docker push docker.pkg.github.com/wardcunningham/seran-wiki:latest
