name: Build & Push Docker Image
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Docker Image
      run: |
        docker build . --file Dockerfile --tag ${GITHUB_SHA:0:8}
    - name: Push Build Image
      run: |
        echo ${{ github.token }} |  docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
        export PKG=docker.pkg.github.com/$(<<<"${{ github.repository }}" tr '[:upper:]' '[:lower:]')/seran-wiki:${GITHUB_SHA:0:8}
        docker tag ${GITHUB_SHA:0:8} $PKG
        docker push $PKG
    - name: Push Latest Image
      if: github.ref == 'refs/heads/master'
      run: |
        echo ${{ github.token }} |  docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
        export PKG=docker.pkg.github.com/$(<<<"${{ github.repository }}" tr '[:upper:]' '[:lower:]')/seran-wiki:latest
        docker tag ${GITHUB_SHA:0:8} $PKG
        docker push $PKG
